[project]
name = "scriberr-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "whisperx>=3.4.0",
    "yt-dlp>=2025.6.30",
]
