version: '3.8'

services:
  whisperlivekit-server:
    build: .
    ports:
      - "9090:9090"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      # Optional: Mount a cache directory for model downloads
      - ./cache:/root/.cache
    restart: unless-stopped
    # For GPU support, uncomment the following lines:
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu] 